services:
  wc_dc_bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      # - ../wc_scoreboard/scores.json:/app/json/score.json
    # restart: unless-stopped
    networks:
      - default
networks:
  default:
    name: wc_dc_bot_network
