name: Discord Webhook Notification

on:
  push:
    branches:
      - main # 指定觸發的分支

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # 檢出代碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 初始化或讀取推送次數
      - name: Setup Push Count
        id: setup_push_count
        run: |
          FILE=push_count.txt
          if [ ! -f $FILE ]; then
            echo 0 > $FILE
          fi
          COUNT=$(cat $FILE)
          echo "::set-output name=count::$COUNT"

      # 增加推送次數並更新文件
      - name: Increment Push Count
        id: increment_push_count
        run: |
          FILE=push_count.txt
          COUNT=$(cat $FILE)
          COUNT=$((COUNT + 1))
          echo $COUNT > $FILE
          echo "::set-output name=count::$COUNT"

      # 傳送 Discord 推播
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                     \"content\": \"WOW ${{ github.actor }} 又組裝了機器人的一個零件！！！\\n居然已經推了${{ steps.increment_push_count.outputs.count }}次耶！\"
                   }" \
               $DISCORD_WEBHOOK_URL

      # 更新推送次數到倉庫
      - name: Commit Push Count
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add push_count.txt
          git commit -m "Update push count to ${{ steps.increment_push_count.outputs.count }}"
          git push
